# Generated by Django 3.2.7 on 2021-10-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20211005_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='country',
            new_name='published_countries',
        ),
    ]
